[project]
name = "heat-transfer-cooling-fin-model"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.5",
    "numpy>=2.3.2",
    "scipy>=1.16.1",
    "seaborn>=0.13.2",
    "tensorflow>=2.14.0",
]
